/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ed.davidnavarroc.proyecto2;

/**
 *
 * @author angel
 */
public class Menu extends javax.swing.JFrame {
    
     private Gestor gestor = new Gestor();
    
     private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistroDepartamentos = new javax.swing.JButton();
        btnRegistroArticulos = new javax.swing.JButton();
        btnEliminarArticulos = new javax.swing.JButton();
        btnTrasladarArticulos = new javax.swing.JButton();
        btnEliminarDepartamentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistroDepartamentos.setText("Registro de Departamentos");
        btnRegistroDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroDepartamentosActionPerformed(evt);
            }
        });

        btnRegistroArticulos.setText("Registro de Artículos");
        btnRegistroArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroArticulosActionPerformed(evt);
            }
        });

        btnEliminarArticulos.setText("Eliminar Artículos");

        btnTrasladarArticulos.setText("Trasladar Artículos");

        btnEliminarDepartamentos.setText("Eliminar Departamentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRegistroDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistroArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrasladarArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnRegistroDepartamentos)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroArticulos)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarArticulos)
                .addGap(18, 18, 18)
                .addComponent(btnTrasladarArticulos)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarDepartamentos)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroDepartamentosActionPerformed
        // TODO add your handling code here:
        RegistroDepartamentos ventanaRegistroDepartamentos = new RegistroDepartamentos();
        ventanaRegistroDepartamentos.setVisible(true);
        ventanaRegistroDepartamentos.recibirGestor(gestor);
        ventanaRegistroDepartamentos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegistroDepartamentosActionPerformed

    private void btnRegistroArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroArticulosActionPerformed
        // TODO add your handling code here:
        RegistroArticulos ventanaRegistroArticulos = new RegistroArticulos();
        ventanaRegistroArticulos.setVisible(true);
        ventanaRegistroArticulos.recibirGestor(gestor);
        ventanaRegistroArticulos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegistroArticulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarArticulos;
    private javax.swing.JButton btnEliminarDepartamentos;
    private javax.swing.JButton btnRegistroArticulos;
    private javax.swing.JButton btnRegistroDepartamentos;
    private javax.swing.JButton btnTrasladarArticulos;
    // End of variables declaration//GEN-END:variables
}
