/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ed.davidnavarroc.proyecto2;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class RegistroArticulos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroArticulos.class.getName());
    
    private Gestor gestor;//Referencia del gestor centralizado
    private Departamento departamentoSeleccionado;//Referencia del departamento actual seleccionado
    
    public void recibirGestor(Gestor gestor){ //Método público para compartir la misma instancia con otras ventanas
        this.gestor = gestor;
        mostrarDepartamentos();
    }
    
    //Método para mostrar los departamentos en la ventana de registro de artículos
    public void mostrarDepartamentos(){
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaElegirDepartamentos.getModel();//Se define el modelo de la tabla
        modeloTabla.setRowCount(0);//Se limpia la tabla para mostrar los datos actualizados
        
        Departamento[] listaDepartamentos = gestor.getDepartamentos();//Se obtiene el arreglo de departamentos
        
        for(int i = 0; i <= gestor.getUltimoDep(); i++){//Recorre desde 0 hasta el último departamento registrado
            Departamento departamento = listaDepartamentos[i];
            if(departamento != null){//Si el objeto de departamento no está vacío o nulo, se muestra en la tabla
                modeloTabla.addRow(new Object[]{departamento.getId(), departamento.getNombre()});
            }
        }
    }

    /**
     * Creates new form RegistroArticulos
     */
    public RegistroArticulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaElegirDepartamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        categoriaArticulo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        idArticulo = new javax.swing.JTextField();
        nombreArticulo = new javax.swing.JTextField();
        btnAgregarArticulo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        depSeleccionado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaElegirDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaElegirDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaElegirDepartamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaElegirDepartamentos);

        jLabel1.setText("Elija el departamento para registrar el artículo");

        jLabel2.setText("Registrar artículos");

        jLabel3.setText("ID");

        jLabel4.setText("Nombre");

        categoriaArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropa y accesorios", "Electrónica", "Hogar y muebles", "Belleza y cuidado personal", "Deportes y aire libre", "Juguetes y juegos", "Alimentos y bebidas" }));
        categoriaArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaArticuloActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoría");

        idArticulo.setEditable(false);
        idArticulo.setText("ID Automático");
        idArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idArticuloActionPerformed(evt);
            }
        });

        nombreArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreArticuloActionPerformed(evt);
            }
        });

        btnAgregarArticulo.setText("Agregar artículo");
        btnAgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArticuloActionPerformed(evt);
            }
        });

        jLabel6.setText("El departamento seleccionado es:");

        depSeleccionado.setEditable(false);
        depSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depSeleccionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nombreArticulo)
                                            .addComponent(categoriaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(54, 54, 54)
                                .addComponent(btnAgregarArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(idArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(categoriaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarArticulo))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(depSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método que define las acciones al hacer click en un departamento de la tabla
    private void tablaElegirDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaElegirDepartamentosMouseClicked
        // TODO add your handling code here:
        int filaClick = tablaElegirDepartamentos.getSelectedRow();//Se obtiene el número de fila en la que el usuario hizo click
        
        if(filaClick != -1){//Si la fila clickeada es valida obtiene el ID del departamento seleccionado
            int idBuscar = (int)tablaElegirDepartamentos.getValueAt(filaClick, 0);
            
            Departamento[] departamentosReg = gestor.getDepartamentos();//Obtiene el arreglo de departamentos desde el gestor
            
            for(int i = 0; i <= gestor.getUltimoDep(); i++){//Recorre los departamentos hasta que el ID coincida con alguno
                Departamento departamento = gestor.getDepartamentos()[i];
                if(departamento.getId() == idBuscar){//Si el ID coincide, se guarda como el departamento seleccionado
                    departamentoSeleccionado = departamento;
                    break;//Se detiene el ciclo porque ya se encontró el departamento 
                }
            }
            idArticulo.setText(String.valueOf(gestor.getIdArticulo()));//Muestra el siguiente ID disponible al momento de ingresar un artículo nuevo
            depSeleccionado.setText(departamentoSeleccionado.getNombre());//Muestra el nombre del departamento selccionado
        }
        
    }//GEN-LAST:event_tablaElegirDepartamentosMouseClicked

    private void categoriaArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaArticuloActionPerformed

    private void idArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idArticuloActionPerformed

    private void nombreArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreArticuloActionPerformed

    //Método que define las acciones al presionar el botón de Agregar Artículo
    private void btnAgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArticuloActionPerformed
        // TODO add your handling code here:
        if(departamentoSeleccionado == null){//Si no hay ningún departamento seleccionado, terminan las funciones
            System.out.println("No hay departamento seleccionado");
            return;
        }
        
        //Obtiene los datos del nuevo artículo desde los campos de texto
        String nomArticulo = nombreArticulo.getText().trim();//Textfield
        String catArticulo = categoriaArticulo.getSelectedItem().toString();//Combo box
        
        if(nomArticulo.isEmpty()){//Si el campo del nombre está vacío, termina sin agregar nada
            System.out.println("Nombre art vacío");
            return;
        }
        
        Articulo articuloNuevo = new Articulo(gestor.getIdArticulo(), nomArticulo, catArticulo);//Crea un nuevo objeto Artículo con el ID consecutivo actual, el nombre y categoría ingresador por el usuario
        
        if(departamentoSeleccionado.agregarArticulo(articuloNuevo)){//Agrega el artículo al departamento seleccionado con el método agregarArtículo
            //Si el artículo se agregó correctamente, el ID se incrementa para el siguiente artículo y el campo del texto se limpia
            gestor.incrementarIdArticulo();
            nombreArticulo.setText("");
            
            //Pruebas en consola
            /*System.out.println("Artículo agregado al departamento: " + departamentoSeleccionado.getNombre());
            System.out.println("Artículos actuales:");*/
            
            Articulo[] listaArticulos = departamentoSeleccionado.getArticulos();//Se guarda en listaArticulos los artículos del departamento seleccionado
            for(int i = departamentoSeleccionado.getFrenteCola(); i<= departamentoSeleccionado.getFinalCola(); i++){//Recorre la cola de artículos desde el frente al final de la cola (FIFO)
                Articulo articulo = listaArticulos[i];
                
                //Pruebas en consola
                /*if(articulo != null){
                    System.out.println("- "+articulo.getId()+ " | " + articulo.getNombre() + " | "+ articulo.getCategoria());
                }*/
            }
            idArticulo.setText(String.valueOf(gestor.getIdArticulo()));//Actualiza en pantalla el ID del siguiente artículo a ingresar

        }else{
            //Pruebas en consola
            System.out.println("no, cola llena");
        }
        
    }//GEN-LAST:event_btnAgregarArticuloActionPerformed

    private void depSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depSeleccionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depSeleccionadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroArticulos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArticulo;
    private javax.swing.JComboBox<String> categoriaArticulo;
    private javax.swing.JTextField depSeleccionado;
    private javax.swing.JTextField idArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreArticulo;
    private javax.swing.JTable tablaElegirDepartamentos;
    // End of variables declaration//GEN-END:variables
}
